/**
 * TitanCrew · DailySummaryBanner
 * Top-of-page greeting with the AI-generated daily summary.
 * Fetches the latest summary from the most recent Foreman Agent run.
 */

"use client";

import { useState, useEffect } from "react";
import { Bot, ChevronDown, ChevronUp, Sparkles } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

interface DailySummaryBannerProps {
  businessName: string;
  ownerName: string;
}

export function DailySummaryBanner({ businessName, ownerName }: DailySummaryBannerProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [expanded, setExpanded] = useState(false);
  const [loading, setLoading] = useState(true);
  const supabase = createClient();

  const greeting = (() => {
    const h = new Date().getHours();
    if (h < 12) return "Good morning";
    if (h < 17) return "Good afternoon";
    return "Good evening";
  })();

  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long", month: "long", day: "numeric",
  });

  useEffect(() => {
    const fetchSummary = async () => {
      try {
        // Get latest foreman run output
        const { data: runs } = await supabase
          .from("agent_runs")
          .select("output_summary, created_at")
          .eq("trigger_event", "daily_morning_sweep")
          .eq("status", "success")
          .order("created_at", { ascending: false })
          .limit(1);

        if (runs && runs.length > 0 && runs[0].output_summary) {
          setSummary(runs[0].output_summary);
        }
      } catch {
        // Fail silently — banner is non-critical
      } finally {
        setLoading(false);
      }
    };

    fetchSummary();
  }, []);

  const previewText = summary
    ? summary.length > 120 ? summary.slice(0, 120) + "..." : summary
    : null;

  return (
    <div className="bg-white rounded-2xl border border-slate-100 agent-card overflow-hidden">
      <div className="flex items-start gap-4 p-4">
        {/* Icon */}
        <div className="w-10 h-10 bg-[#1A2744] rounded-xl flex items-center justify-center flex-shrink-0">
          <Sparkles className="w-5 h-5 text-[#FF6B00]" />
        </div>

        {/* Content */}
        <div className="flex-1 min-w-0">
          <div className="flex items-start justify-between gap-4">
            <div>
              <h2 className="text-base font-bold text-[#1A2744]">
                {greeting}, {ownerName.split(" ")[0]}
              </h2>
              <p className="text-xs text-slate-400 mt-0.5">{today} · {businessName}</p>
            </div>

            {summary && (
              <button
                onClick={() => setExpanded(!expanded)}
                className="flex items-center gap-1 text-xs text-slate-500 hover:text-[#1A2744] transition-colors flex-shrink-0"
              >
                {expanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
                {expanded ? "Less" : "More"}
              </button>
            )}
          </div>

          {/* Summary text */}
          <div className="mt-2">
            {loading && (
              <div className="flex items-center gap-2 text-sm text-slate-400">
                <Bot className="w-3.5 h-3.5 animate-pulse" />
                <span>Foreman AI preparing your briefing...</span>
              </div>
            )}

            {!loading && !summary && (
              <div className="flex items-center gap-2 text-sm text-slate-500">
                <Bot className="w-3.5 h-3.5 text-[#FF6B00]" />
                <span>Daily briefing runs at 6:00am. Check back tomorrow morning!</span>
              </div>
            )}

            {!loading && summary && (
              <div>
                <p className="text-sm text-slate-600 leading-relaxed">
                  {expanded ? summary : previewText}
                </p>
                {expanded && (
                  <div className="flex items-center gap-1 mt-2">
                    <Bot className="w-3 h-3 text-slate-400" />
                    <span className="text-xs text-slate-400">Generated by Foreman AI</span>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
