// Supabase generated types for TitanCrew database
// Covers all tables used by the agents package

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// Generic table shape that Supabase's createClient<Database> accepts
type AnyTable = {
  Row: Record<string, unknown>;
  Insert: Record<string, unknown>;
  Update: Record<string, unknown>;
  Relationships: unknown[];
};

type AnyFunction = {
  Args: Record<string, unknown>;
  Returns: unknown;
};

// Enum types matching schema
export type PlanTier = 'lite' | 'growth' | 'scale';
export type SubscriptionStatus = 'trialing' | 'active' | 'past_due' | 'canceled' | 'paused';
export type AgentType =
  | 'scheduler' | 'parts_inventory' | 'customer_comm'
  | 'finance_invoice' | 'foreman_predictor' | 'tech_dispatch'
  | 'lead_hunter' | 'demo_creator' | 'onboarder'
  | 'performance_optimizer' | 'billing_churn_preventer';
export type AgentStatus = 'idle' | 'running' | 'waiting_human' | 'error' | 'disabled';
export type JobStatus = 'lead' | 'scheduled' | 'dispatched' | 'in_progress' | 'completed' | 'invoiced' | 'paid' | 'canceled';
export type ActionRisk = 'low' | 'medium' | 'high' | 'critical';
export type ConfirmationStatus = 'pending' | 'approved' | 'rejected' | 'timed_out';
export type TradeType = 'plumbing' | 'electrical' | 'hvac' | 'general' | 'roofing' | 'pest_control' | 'other';
export type CommsChannel = 'sms' | 'voice' | 'email' | 'push';
export type LeadStage = 'signal_detected' | 'qualified' | 'demo_sent' | 'follow_up' | 'trial_started' | 'converted' | 'dead';

export type Database = {
  public: {
    Tables: {
      // Named tables — typed for IDE support
      agent_memory: {
        Row: {
          id: string;
          account_id: string | null;
          memory_type: string;
          source_agent: AgentType | null;
          content: string;
          metadata: Json;
          embedding: string | null;
          relevance_score: number;
          last_accessed: string | null;
          access_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          account_id?: string | null;
          memory_type: string;
          source_agent?: AgentType | null;
          content: string;
          metadata?: Json;
          embedding?: string | null;
          relevance_score?: number;
          last_accessed?: string | null;
          access_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          account_id?: string | null;
          memory_type?: string;
          source_agent?: AgentType | null;
          content?: string;
          metadata?: Json;
          embedding?: string | null;
          relevance_score?: number;
          last_accessed?: string | null;
          access_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      agent_runs: {
        Row: {
          id: string;
          agent_id: string;
          account_id: string;
          run_type: string;
          trigger_event: string | null;
          status: string;
          started_at: string;
          completed_at: string | null;
          duration_ms: number | null;
          input_tokens: number;
          output_tokens: number;
          cost_usd: number;
          model_used: string | null;
          actions_taken: Json;
          output_summary: string | null;
          error_message: string | null;
          langsmith_run_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          agent_id: string;
          account_id: string;
          run_type: string;
          trigger_event?: string | null;
          status?: string;
          started_at?: string;
          completed_at?: string | null;
          duration_ms?: number | null;
          input_tokens?: number;
          output_tokens?: number;
          cost_usd?: number;
          model_used?: string | null;
          actions_taken?: Json;
          output_summary?: string | null;
          error_message?: string | null;
          langsmith_run_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          agent_id?: string;
          account_id?: string;
          run_type?: string;
          trigger_event?: string | null;
          status?: string;
          started_at?: string;
          completed_at?: string | null;
          duration_ms?: number | null;
          input_tokens?: number;
          output_tokens?: number;
          cost_usd?: number;
          model_used?: string | null;
          actions_taken?: Json;
          output_summary?: string | null;
          error_message?: string | null;
          langsmith_run_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      hil_confirmations: {
        Row: {
          id: string;
          account_id: string;
          agent_run_id: string | null;
          created_at: string;
          expires_at: string;
          action_type: string;
          risk_level: ActionRisk;
          description: string;
          amount: number | null;
          payload: Json;
          sent_via: CommsChannel;
          sent_to: string;
          twilio_sid: string | null;
          status: ConfirmationStatus;
          responded_at: string | null;
          response_token: string;
          rejection_reason: string | null;
        };
        Insert: {
          id?: string;
          account_id: string;
          agent_run_id?: string | null;
          created_at?: string;
          expires_at?: string;
          action_type: string;
          risk_level?: ActionRisk;
          description: string;
          amount?: number | null;
          payload?: Json;
          sent_via?: CommsChannel;
          sent_to: string;
          twilio_sid?: string | null;
          status?: ConfirmationStatus;
          responded_at?: string | null;
          response_token?: string;
          rejection_reason?: string | null;
        };
        Update: {
          id?: string;
          account_id?: string;
          agent_run_id?: string | null;
          created_at?: string;
          expires_at?: string;
          action_type?: string;
          risk_level?: ActionRisk;
          description?: string;
          amount?: number | null;
          payload?: Json;
          sent_via?: CommsChannel;
          sent_to?: string;
          twilio_sid?: string | null;
          status?: ConfirmationStatus;
          responded_at?: string | null;
          response_token?: string;
          rejection_reason?: string | null;
        };
        Relationships: [];
      };
      accounts: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          owner_name: string;
          business_name: string;
          email: string;
          phone: string | null;
          owner_phone: string | null;
          twilio_phone_number: string | null;
          twilio_a2p_registered: boolean;
          referral_code: string | null;
          owner_user_id: string | null;
          trade_type: TradeType;
          state: string | null;
          city: string | null;
          zip: string | null;
          tech_count: number;
          years_in_business: number | null;
          avg_job_value: number | null;
          website_url: string | null;
          plan: PlanTier;
          subscription_status: SubscriptionStatus;
          stripe_customer_id: string | null;
          stripe_sub_id: string | null;
          trial_ends_at: string;
          mrr: number;
          rev_share_opted_in: boolean;
          onboarded_at: string | null;
          crew_deployed_at: string | null;
          onboard_step: number;
          jobs_booked_30d: number;
          jobs_ai_booked_30d: number;
          revenue_ai_30d: number;
          nps_score: number | null;
          churn_risk_score: number;
          last_active_at: string | null;
          timezone: string;
          notification_prefs: Json;
          integrations: Json;
          feature_flags: Json;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          owner_name: string;
          business_name: string;
          email: string;
          phone?: string | null;
          owner_phone?: string | null;
          twilio_phone_number?: string | null;
          twilio_a2p_registered?: boolean;
          referral_code?: string | null;
          owner_user_id?: string | null;
          trade_type?: TradeType;
          state?: string | null;
          city?: string | null;
          zip?: string | null;
          tech_count?: number;
          years_in_business?: number | null;
          avg_job_value?: number | null;
          website_url?: string | null;
          plan?: PlanTier;
          subscription_status?: SubscriptionStatus;
          stripe_customer_id?: string | null;
          stripe_sub_id?: string | null;
          trial_ends_at?: string;
          mrr?: number;
          rev_share_opted_in?: boolean;
          onboarded_at?: string | null;
          crew_deployed_at?: string | null;
          onboard_step?: number;
          jobs_booked_30d?: number;
          jobs_ai_booked_30d?: number;
          revenue_ai_30d?: number;
          nps_score?: number | null;
          churn_risk_score?: number;
          last_active_at?: string | null;
          timezone?: string;
          notification_prefs?: Json;
          integrations?: Json;
          feature_flags?: Json;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          owner_name?: string;
          business_name?: string;
          email?: string;
          phone?: string | null;
          owner_phone?: string | null;
          twilio_phone_number?: string | null;
          twilio_a2p_registered?: boolean;
          referral_code?: string | null;
          owner_user_id?: string | null;
          trade_type?: TradeType;
          state?: string | null;
          city?: string | null;
          zip?: string | null;
          tech_count?: number;
          years_in_business?: number | null;
          avg_job_value?: number | null;
          website_url?: string | null;
          plan?: PlanTier;
          subscription_status?: SubscriptionStatus;
          stripe_customer_id?: string | null;
          stripe_sub_id?: string | null;
          trial_ends_at?: string;
          mrr?: number;
          rev_share_opted_in?: boolean;
          onboarded_at?: string | null;
          crew_deployed_at?: string | null;
          onboard_step?: number;
          jobs_booked_30d?: number;
          jobs_ai_booked_30d?: number;
          revenue_ai_30d?: number;
          nps_score?: number | null;
          churn_risk_score?: number;
          last_active_at?: string | null;
          timezone?: string;
          notification_prefs?: Json;
          integrations?: Json;
          feature_flags?: Json;
        };
        Relationships: [];
      };
      jobs: {
        Row: {
          id: string;
          account_id: string;
          customer_id: string | null;
          technician_id: string | null;
          created_at: string;
          updated_at: string;
          title: string;
          description: string | null;
          trade_type: TradeType | null;
          job_type: string | null;
          status: JobStatus;
          priority: number;
          scheduled_start: string | null;
          scheduled_end: string | null;
          actual_start: string | null;
          actual_end: string | null;
          address: string | null;
          lat: number | null;
          lng: number | null;
          estimate_amount: number | null;
          invoice_amount: number | null;
          paid_amount: number | null;
          invoice_id: string | null;
          payment_status: string | null;
          booked_by_ai: boolean;
          agent_id: string | null;
          ai_confidence: number | null;
          source: string | null;
          tags: string[];
          notes: string | null;
          parts_needed: Json;
          embedding: string | null;
        };
        Insert: {
          id?: string;
          account_id: string;
          customer_id?: string | null;
          technician_id?: string | null;
          created_at?: string;
          updated_at?: string;
          title: string;
          description?: string | null;
          trade_type?: TradeType | null;
          job_type?: string | null;
          status?: JobStatus;
          priority?: number;
          scheduled_start?: string | null;
          scheduled_end?: string | null;
          actual_start?: string | null;
          actual_end?: string | null;
          address?: string | null;
          lat?: number | null;
          lng?: number | null;
          estimate_amount?: number | null;
          invoice_amount?: number | null;
          paid_amount?: number | null;
          invoice_id?: string | null;
          payment_status?: string | null;
          booked_by_ai?: boolean;
          agent_id?: string | null;
          ai_confidence?: number | null;
          source?: string | null;
          tags?: string[];
          notes?: string | null;
          parts_needed?: Json;
          embedding?: string | null;
        };
        Update: {
          id?: string;
          account_id?: string;
          customer_id?: string | null;
          technician_id?: string | null;
          created_at?: string;
          updated_at?: string;
          title?: string;
          description?: string | null;
          trade_type?: TradeType | null;
          job_type?: string | null;
          status?: JobStatus;
          priority?: number;
          scheduled_start?: string | null;
          scheduled_end?: string | null;
          actual_start?: string | null;
          actual_end?: string | null;
          address?: string | null;
          lat?: number | null;
          lng?: number | null;
          estimate_amount?: number | null;
          invoice_amount?: number | null;
          paid_amount?: number | null;
          invoice_id?: string | null;
          payment_status?: string | null;
          booked_by_ai?: boolean;
          agent_id?: string | null;
          ai_confidence?: number | null;
          source?: string | null;
          tags?: string[];
          notes?: string | null;
          parts_needed?: Json;
          embedding?: string | null;
        };
        Relationships: [];
      };
      parts: {
        Row: {
          id: string;
          account_id: string;
          created_at: string;
          updated_at: string;
          sku: string | null;
          name: string;
          description: string | null;
          supplier: string | null;
          supplier_sku: string | null;
          unit_cost: number | null;
          qty_on_hand: number;
          qty_min_stock: number;
          qty_on_order: number;
          last_ordered_at: string | null;
          last_used_at: string | null;
          usage_30d: number;
          auto_reorder: boolean;
          tags: string[];
        };
        Insert: {
          id?: string;
          account_id: string;
          created_at?: string;
          updated_at?: string;
          sku?: string | null;
          name: string;
          description?: string | null;
          supplier?: string | null;
          supplier_sku?: string | null;
          unit_cost?: number | null;
          qty_on_hand?: number;
          qty_min_stock?: number;
          qty_on_order?: number;
          last_ordered_at?: string | null;
          last_used_at?: string | null;
          usage_30d?: number;
          auto_reorder?: boolean;
          tags?: string[];
        };
        Update: {
          id?: string;
          account_id?: string;
          created_at?: string;
          updated_at?: string;
          sku?: string | null;
          name?: string;
          description?: string | null;
          supplier?: string | null;
          supplier_sku?: string | null;
          unit_cost?: number | null;
          qty_on_hand?: number;
          qty_min_stock?: number;
          qty_on_order?: number;
          last_ordered_at?: string | null;
          last_used_at?: string | null;
          usage_30d?: number;
          auto_reorder?: boolean;
          tags?: string[];
        };
        Relationships: [];
      };
      purchase_orders: {
        Row: {
          id: string;
          account_id: string;
          created_at: string;
          updated_at: string;
          supplier: string;
          status: string;
          total_amount: number | null;
          submitted_at: string | null;
          expected_at: string | null;
          received_at: string | null;
          line_items: Json;
          created_by_ai: boolean;
          approved_by: string | null;
          external_po_id: string | null;
        };
        Insert: {
          id?: string;
          account_id: string;
          created_at?: string;
          updated_at?: string;
          supplier: string;
          status?: string;
          total_amount?: number | null;
          submitted_at?: string | null;
          expected_at?: string | null;
          received_at?: string | null;
          line_items?: Json;
          created_by_ai?: boolean;
          approved_by?: string | null;
          external_po_id?: string | null;
        };
        Update: {
          id?: string;
          account_id?: string;
          created_at?: string;
          updated_at?: string;
          supplier?: string;
          status?: string;
          total_amount?: number | null;
          submitted_at?: string | null;
          expected_at?: string | null;
          received_at?: string | null;
          line_items?: Json;
          created_by_ai?: boolean;
          approved_by?: string | null;
          external_po_id?: string | null;
        };
        Relationships: [];
      };
      agent_instances: {
        Row: {
          id: string;
          account_id: string;
          created_at: string;
          updated_at: string;
          agent_type: AgentType;
          status: AgentStatus;
          version: string;
          is_enabled: boolean;
          graph_state: Json;
          checkpoint_id: string | null;
          thread_id: string | null;
          actions_24h: number;
          errors_24h: number;
          avg_latency_ms: number | null;
          token_cost_30d: number;
          system_prompt_override: string | null;
          config: Json;
          last_run_at: string | null;
          last_error: string | null;
        };
        Insert: {
          id?: string;
          account_id: string;
          created_at?: string;
          updated_at?: string;
          agent_type: AgentType;
          status?: AgentStatus;
          version?: string;
          is_enabled?: boolean;
          graph_state?: Json;
          checkpoint_id?: string | null;
          thread_id?: string | null;
          actions_24h?: number;
          errors_24h?: number;
          avg_latency_ms?: number | null;
          token_cost_30d?: number;
          system_prompt_override?: string | null;
          config?: Json;
          last_run_at?: string | null;
          last_error?: string | null;
        };
        Update: {
          id?: string;
          account_id?: string;
          created_at?: string;
          updated_at?: string;
          agent_type?: AgentType;
          status?: AgentStatus;
          version?: string;
          is_enabled?: boolean;
          graph_state?: Json;
          checkpoint_id?: string | null;
          thread_id?: string | null;
          actions_24h?: number;
          errors_24h?: number;
          avg_latency_ms?: number | null;
          token_cost_30d?: number;
          system_prompt_override?: string | null;
          config?: Json;
          last_run_at?: string | null;
          last_error?: string | null;
        };
        Relationships: [];
      };
      trade_customers: {
        Row: {
          id: string;
          account_id: string;
          created_at: string;
          updated_at: string;
          name: string;
          email: string | null;
          phone: string;
          address: string | null;
          city: string | null;
          state: string | null;
          zip: string | null;
          lat: number | null;
          lng: number | null;
          customer_since: string | null;
          total_jobs: number;
          total_spent: number;
          avg_job_value: number | null;
          last_service_at: string | null;
          preferred_tech: string | null;
          ltv_prediction: number | null;
          next_service_at: string | null;
          tags: string[];
          notes: string | null;
          comms_opt_out: boolean;
          embedding: string | null;
        };
        Insert: {
          id?: string;
          account_id: string;
          created_at?: string;
          updated_at?: string;
          name: string;
          email?: string | null;
          phone: string;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip?: string | null;
          lat?: number | null;
          lng?: number | null;
          customer_since?: string | null;
          total_jobs?: number;
          total_spent?: number;
          avg_job_value?: number | null;
          last_service_at?: string | null;
          preferred_tech?: string | null;
          ltv_prediction?: number | null;
          next_service_at?: string | null;
          tags?: string[];
          notes?: string | null;
          comms_opt_out?: boolean;
          embedding?: string | null;
        };
        Update: {
          id?: string;
          account_id?: string;
          created_at?: string;
          updated_at?: string;
          name?: string;
          email?: string | null;
          phone?: string;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip?: string | null;
          lat?: number | null;
          lng?: number | null;
          customer_since?: string | null;
          total_jobs?: number;
          total_spent?: number;
          avg_job_value?: number | null;
          last_service_at?: string | null;
          preferred_tech?: string | null;
          ltv_prediction?: number | null;
          next_service_at?: string | null;
          tags?: string[];
          notes?: string | null;
          comms_opt_out?: boolean;
          embedding?: string | null;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: string;
          created_at: string;
          account_id: string | null;
          agent_run_id: string | null;
          user_id: string | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          before_state: Json | null;
          after_state: Json | null;
          ip_address: string | null;
          metadata: Json;
        };
        Insert: {
          id?: string;
          created_at?: string;
          account_id?: string | null;
          agent_run_id?: string | null;
          user_id?: string | null;
          action: string;
          entity_type?: string | null;
          entity_id?: string | null;
          before_state?: Json | null;
          after_state?: Json | null;
          ip_address?: string | null;
          metadata?: Json;
        };
        Update: {
          id?: string;
          created_at?: string;
          account_id?: string | null;
          agent_run_id?: string | null;
          user_id?: string | null;
          action?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          before_state?: Json | null;
          after_state?: Json | null;
          ip_address?: string | null;
          metadata?: Json;
        };
        Relationships: [];
      };
      technicians: {
        Row: {
          id: string;
          account_id: string;
          created_at: string;
          name: string;
          phone: string | null;
          email: string | null;
          trade_type: TradeType | null;
          skill_tags: string[];
          is_active: boolean;
          hourly_rate: number | null;
          efficiency_score: number;
          calendar_id: string | null;
          availability: Json | null;
          created_by_agent: boolean;
        };
        Insert: {
          id?: string;
          account_id: string;
          created_at?: string;
          name: string;
          phone?: string | null;
          email?: string | null;
          trade_type?: TradeType | null;
          skill_tags?: string[];
          is_active?: boolean;
          hourly_rate?: number | null;
          efficiency_score?: number;
          calendar_id?: string | null;
          availability?: Json | null;
          created_by_agent?: boolean;
        };
        Update: {
          id?: string;
          account_id?: string;
          created_at?: string;
          name?: string;
          phone?: string | null;
          email?: string | null;
          trade_type?: TradeType | null;
          skill_tags?: string[];
          is_active?: boolean;
          hourly_rate?: number | null;
          efficiency_score?: number;
          calendar_id?: string | null;
          availability?: Json | null;
          created_by_agent?: boolean;
        };
        Relationships: [];
      };
      comms_log: {
        Row: {
          id: string;
          account_id: string;
          customer_id: string | null;
          job_id: string | null;
          agent_run_id: string | null;
          created_at: string;
          direction: string;
          channel: CommsChannel;
          to_address: string;
          from_address: string | null;
          subject: string | null;
          body: string;
          status: string | null;
          external_id: string | null;
          cost_usd: number | null;
          ai_generated: boolean;
          sentiment_score: number | null;
          intent_tags: string[];
        };
        Insert: {
          id?: string;
          account_id: string;
          customer_id?: string | null;
          job_id?: string | null;
          agent_run_id?: string | null;
          created_at?: string;
          direction?: string;
          channel: CommsChannel;
          to_address: string;
          from_address?: string | null;
          subject?: string | null;
          body: string;
          status?: string | null;
          external_id?: string | null;
          cost_usd?: number | null;
          ai_generated?: boolean;
          sentiment_score?: number | null;
          intent_tags?: string[];
        };
        Update: {
          id?: string;
          account_id?: string;
          customer_id?: string | null;
          job_id?: string | null;
          agent_run_id?: string | null;
          created_at?: string;
          direction?: string;
          channel?: CommsChannel;
          to_address?: string;
          from_address?: string | null;
          subject?: string | null;
          body?: string;
          status?: string | null;
          external_id?: string | null;
          cost_usd?: number | null;
          ai_generated?: boolean;
          sentiment_score?: number | null;
          intent_tags?: string[];
        };
        Relationships: [];
      };
      // Catch-all for any other tables used in the codebase
      [tableName: string]: AnyTable;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      search_agent_memory: {
        Args: {
          p_account_id: string;
          p_query_embedding: string;
          p_memory_type: string | null;
          p_limit: number;
        };
        Returns: Array<{
          id: string;
          content: string;
          metadata: Json;
          similarity: number;
        }>;
      };
      increment: {
        Args: { id: string };
        Returns: number;
      };
      // Catch-all for other functions
      [funcName: string]: AnyFunction;
    };
    Enums: {
      [_ in never]: never;
    };
  };
};
